from sinq3.models import Question
from sinq3.models import QuestionImage

from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.template import Context, loader

from django.template import RequestContext

from django.http import Http404

from django.shortcuts import render_to_response

# Import forms:
from sinq3.forms import QuestionForm
from sinq3.forms import QuestionImageForm

from django.utils import simplejson
from django.core import serializers

# For @csrf_exempt decorator (https://docs.djangoproject.com/en/1.2/ref/contrib/csrf/#exceptions).  This is needed for POSTs that do not have a CSRF token (generated by Django).
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

def home(request):
	t = loader.get_template('home.html')
	c = Context({})
	return HttpResponse(t.render(c))

@csrf_exempt
def question_index(request):
	if request.method == 'GET':

		# Retreive request data
		format = request.GET['format'] if 'format' in request.GET else None

		latest_question_list = Question.objects.all()
		#.order_by('-creation_timestamp')[:5]

		if format == 'json':
			# Serialize questions in JSON format
			# i.e., https://docs.djangoproject.com/en/dev/topics/serialization/
			serialized_questions = serializers.serialize('json', latest_question_list, fields=('text'))
			return HttpResponse(serialized_questions, mimetype="application/json")

		else:
			#if len(latest_question_list) > 0: # this is not efficient, use next line:
			if latest_question_list.count() > 0:
				output = ', '.join([q.text for q in latest_question_list])
			else:
				output = 'No questions!'
			t = loader.get_template('questions/index.html')
			c = Context({
					'latest_question_list': latest_question_list,
					'format': format
				})
			return HttpResponse(t.render(c))

def question_create(request):
	if request.method == 'POST':
		form = QuestionForm(request.POST, request.FILES)
		if form.is_valid():
			# Create new question image and store in DB
			question_text = request.POST['question_text']

			question = Question(text = question_text)
			question.save()

			return HttpResponseRedirect(reverse('sinq3.views.question_view', args=(question.id,)))
	else:
		form = QuestionForm() # An empty, unbound form

	return render_to_response(
			'questions/question_create.html',
			{
				'form': form
			},
			context_instance=RequestContext(request)
		)

@csrf_exempt
def question_create_api(request):
	if request.method == 'POST':

		question_json = request.body
		json_data = simplejson.loads(question_json)

		try:
			#data = json_data[0]
			question_data = json_data['question']

			question = Question(text = question_data['text'])
			question.save()

			# Serialize questions in JSON format
			# i.e., https://docs.djangoproject.com/en/dev/topics/serialization/
			serialized_questions = serializers.serialize('json', [question], fields=('text'))
			return HttpResponse(serialized_questions, mimetype="application/json")

		except KeyError:
			HttpResponseServerError("Malformed data!")

		return HttpResponse(object)

	else:
		HttpResponseServerError("Not POST.  Must POST to this URL.")


def question_edit(request, question_id):
	try:
		question = Question.objects.get(id=question_id)
	except:
		raise Http404

	if request.method == 'POST':
		form = QuestionForm(request.POST)
		if form.is_valid():
			# Update question properties
			question.text = request.POST['question_text']
			question.save()

			return HttpResponseRedirect(reverse('sinq3.views.question_view', args=(question.id,)))
	else:
		form = QuestionForm() # An empty, unbound form

	return render_to_response(
			'questions/question_edit.html',
			{
				'question': question,
				'form': form
			},
			context_instance=RequestContext(request)
		)

@csrf_exempt
def question_read(request, question_id):

	if request.method == 'GET':
		try:
			question = Question.objects.get(id=question_id)
		except:
			raise Http404

		# Retreive request data
		format = request.GET['format'] if 'format' in request.GET else None

		if format == 'json':
			# Serialize questions in JSON format
			# i.e., https://docs.djangoproject.com/en/dev/topics/serialization/
			serialized_questions = serializers.serialize('json', [question], fields=('text'))
			return HttpResponse(serialized_questions, mimetype="application/json")

		else:
			# Display the question
			t = loader.get_template('questions/question_view.html')
			c = Context({
					'question': question
				})

			return HttpResponse(t.render(c))

def question_image_create(request, question_id):
	# Get question to which the image will be attached.
	try:
		question = Question.objects.get(id=question_id)
	except:
		raise Http404

	# Save photo if POST
	if request.method == 'POST':
		form = QuestionImageForm(request.POST, request.FILES)

		if form.is_valid():
			# Create new question image and store in DB
			new_question_image          = QuestionImage(image = request.FILES['question_image'])
			new_question_image.question = question
			new_question_image.save()

			return HttpResponseRedirect(reverse('sinq3.views.question_view', args=(question.id,)))
	else:
		form = QuestionImageForm() # An empty, unbound form

	return render_to_response(
			'question_images/create.html',
			{
				'question': question,
				'form': form
			},
			context_instance=RequestContext(request)
		)

@csrf_exempt
def question_image_create_api(request, question_id):
	# Get question to which the image will be attached.
	try:
		question = Question.objects.get(id=question_id)
	except:
		raise Http404

	# Save photo if POST
	if request.method == 'POST':
		form = QuestionImageForm(request.POST, request.FILES)

		if form.is_valid():
			# Create new question image and store in DB
			new_question_image          = QuestionImage(image = request.FILES['question_image'])
			new_question_image.question = question
			new_question_image.save()

			# Serialize questions in JSON format
			# i.e., https://docs.djangoproject.com/en/dev/topics/serialization/
			serialized_question_image = serializers.serialize('json', [new_question_image], fields=('text'))
			return HttpResponse(serialized_question_image, mimetype="application/json")
	else:
		raise Http500

@csrf_exempt
def question_image_read(request, question_id):
	if request.method == 'GET':
		try:
			question = Question.objects.get(id=question_id)
			question_images = QuestionImage.objects.filter(question_id=question.id)
		except:
			raise Http404

		# Retreive request data
		format = request.GET['format'] if 'format' in request.GET else None

		if format == 'json':
			# Serialize questions in JSON format
			# i.e., https://docs.djangoproject.com/en/dev/topics/serialization/
			serialized_questions = serializers.serialize('json', question_images)
			return HttpResponse(serialized_questions, mimetype="application/json")